// AUTO-GENERATED by better-intl. Do not edit by hand.
// Regenerated automatically by the Next.js plugin on dev/build.

/* eslint-disable */
import { createI18n } from "better-intl/runtime";

export const translations = {
	en: {
		homepage: {
			hero: {
				title: (v: { name: string }) => `Hello ${v.name}`,
				subtitle: "Welcome",
			},
		},
	},
	pt: {
		homepage: {
			hero: {
				title: (v: { name: string }) => `Olá ${v.name}`,
				subtitle: "Bem-vindo",
			},
		},
	},
} as const;

export type Locale = keyof typeof translations;

/** Runtime config for `better-intl/runtime`, baked into the helpers below. */
export const intlConfig = {
	"defaultLocale": "en",
	"locales": [
		"en",
		"pt"
	],
	"storage": {
		"type": "cookie",
		"key": "locale"
	}
} as const;

// Helpers bound to `translations` + `intlConfig` once. Import `t` anywhere
// (sync on both client and server); call `setLocale()` once per request in the
// root layout; call `updateLocale(locale)` to persist a new preference.
const i18n = createI18n(translations, intlConfig);
export const { t, setLocale, updateLocale } = i18n;
