// AUTO-GENERATED by better-intl. Do not edit by hand.
// Regenerated automatically by the Next.js plugin on dev/build.

/* eslint-disable */

export const t = {
	en: {
		homepage: {
			hero: {
				title: (v: { name: string }) => `Hello ${v.name}`,
				subtitle: "Welcome",
			},
		},
	},
	pt: {
		homepage: {
			hero: {
				title: (v: { name: string }) => `Olá ${v.name}`,
				subtitle: "Bem-vindo",
			},
		},
	},
} as const;

export type Locale = keyof typeof t;

export function getT<L extends Locale>(locale: L): (typeof t)[L] {
	return t[locale];
}
