// AUTO-GENERATED by i18n-gen. Do not edit by hand.
// Run `i18n-gen` (or the i18n:gen script) to regenerate.

/* eslint-disable */

export const t = {
	en: {
		homepage: {
			hero: {
				title: (v: { name: string }) => `Hello ${v.name}`,
				subtitle: "Welcome",
			},
		},
	},
	pt: {
		homepage: {
			hero: {
				title: (v: { name: string }) => `Olá ${v.name}`,
				subtitle: "Bem-vindo",
			},
		},
	},
} as const;

export type Locale = keyof typeof t;

export function getT<L extends Locale>(locale: L): (typeof t)[L] {
	return t[locale];
}
