import type { LeafValue, TreeNode } from "../types.js";
import { placeholders } from "./placeholders.js";

const INDENT = "\t";

/** Quote a plain string as a JS string literal. */
function stringLiteral(value: string): string {
	return JSON.stringify(value);
}

/**
 * Escape a literal segment so it is safe inside a template literal: backslash,
 * backtick, and `$` (to avoid accidental `${` interpolation).
 */
function escapeTemplate(segment: string): string {
	return segment.replace(/[\\`$]/g, "\\$&");
}

/**
 * Emit an interpolation arrow function for a string containing `{token}`s.
 * `"Olá {name}"` -> `(v: { name: string }) => \`Olá ${v.name}\``
 */
function interpFn(value: string, tokens: string[]): string {
	const parts = value.split(/(\{\w+\})/g);
	const body = parts
		.map((part) => {
			const m = /^\{(\w+)\}$/.exec(part);
			if (m) return "${v." + m[1] + "}";
			return escapeTemplate(part);
		})
		.join("");
	const argType = tokens.map((t) => `${t}: string`).join("; ");
	return `(v: { ${argType} }) => \`${body}\``;
}

/** A leaf string becomes either a quoted string or an interpolation function. */
function emitLeafString(value: string): string {
	const tokens = placeholders(value);
	return tokens.length > 0 ? interpFn(value, tokens) : stringLiteral(value);
}

/** Recursively emit a leaf value object (nested string maps). */
function emitLeafValue(value: LeafValue, depth: number): string {
	const pad = INDENT.repeat(depth);
	const inner = INDENT.repeat(depth + 1);
	const lines = Object.entries(value).map(([key, val]) => {
		const rendered =
			typeof val === "string"
				? emitLeafString(val)
				: emitLeafValue(val, depth + 1);
		return `${inner}${propKey(key)}: ${rendered},`;
	});
	return `{\n${lines.join("\n")}\n${pad}}`;
}

/** Quote a property key only when it is not a valid identifier. */
function propKey(key: string): string {
	return /^[A-Za-z_$][\w$]*$/.test(key) ? key : JSON.stringify(key);
}

/** Recursively emit a tree node: merged folder children + leaf keys. */
function emitNode(node: TreeNode, depth: number): string {
	const pad = INDENT.repeat(depth);
	const inner = INDENT.repeat(depth + 1);
	const lines: string[] = [];
	const seen = new Set<string>();

	// Folder children first.
	for (const [name, child] of [...node.children.entries()].sort()) {
		seen.add(name);
		lines.push(`${inner}${propKey(name)}: ${emitNode(child, depth + 1)},`);
	}

	// Leaf keys at this level (a `t.ts` colocated with folders).
	if (node.leaf) {
		for (const [key, val] of Object.entries(node.leaf.value)) {
			if (seen.has(key)) {
				throw new Error(
					`Key collision in "${node.leaf.file}": "${key}" is both a folder and a leaf key.`,
				);
			}
			const rendered =
				typeof val === "string"
					? emitLeafString(val)
					: emitLeafValue(val, depth + 1);
			lines.push(`${inner}${propKey(key)}: ${rendered},`);
		}
	}

	if (lines.length === 0) return "{}";
	return `{\n${lines.join("\n")}\n${pad}}`;
}

const HEADER = `// AUTO-GENERATED by i18n-gen. Do not edit by hand.
// Run \`i18n-gen\` (or the i18n:gen script) to regenerate.

/* eslint-disable */
`;

/**
 * Emit the full generated module source: the `t` object, the `Locale` type, and
 * the `getT` accessor. `tree.children` are the locales.
 */
export function emit(tree: TreeNode): string {
	const body = emitNode(tree, 0);
	return `${HEADER}
export const t = ${body} as const;

export type Locale = keyof typeof t;

export function getT<L extends Locale>(locale: L): (typeof t)[L] {
	return t[locale];
}
`;
}
