import type { I18nConfig, LeafValue } from "../types.js";
import { placeholders } from "./placeholders.js";

const INDENT = "\t";

/** Quote a plain string as a JS string literal. */
function stringLiteral(value: string): string {
	return JSON.stringify(value);
}

/**
 * Escape a literal segment so it is safe inside a template literal: backslash,
 * backtick, and `$` (to avoid accidental `${` interpolation).
 */
function escapeTemplate(segment: string): string {
	return segment.replace(/[\\`$]/g, "\\$&");
}

/**
 * Emit an interpolation arrow function for a string containing `{token}`s.
 * `"Olá {name}"` -> `(v: { name: string }) => \`Olá ${v.name}\``
 */
function interpFn(value: string, tokens: string[]): string {
	const parts = value.split(/(\{\w+\})/g);
	const body = parts
		.map((part) => {
			const m = /^\{(\w+)\}$/.exec(part);
			if (m) return "${v." + m[1] + "}";
			return escapeTemplate(part);
		})
		.join("");
	const argType = tokens.map((t) => `${t}: string`).join("; ");
	return `(v: { ${argType} }) => \`${body}\``;
}

/** A leaf string becomes either a quoted string or an interpolation function. */
function emitLeafString(value: string): string {
	const tokens = placeholders(value);
	return tokens.length > 0 ? interpFn(value, tokens) : stringLiteral(value);
}

/** Recursively emit a leaf value object (nested string maps). */
function emitLeafValue(value: LeafValue, depth: number): string {
	const pad = INDENT.repeat(depth);
	const inner = INDENT.repeat(depth + 1);
	const lines = Object.entries(value).map(([key, val]) => {
		const rendered =
			typeof val === "string"
				? emitLeafString(val)
				: emitLeafValue(val, depth + 1);
		return `${inner}${propKey(key)}: ${rendered},`;
	});
	if (lines.length === 0) return "{}";
	return `{\n${lines.join("\n")}\n${pad}}`;
}

/** Quote a property key only when it is not a valid identifier. */
function propKey(key: string): string {
	return /^[A-Za-z_$][\w$]*$/.test(key) ? key : JSON.stringify(key);
}

const HEADER = `// AUTO-GENERATED by better-intl. Do not edit by hand.
// Regenerated automatically by the Next.js plugin on dev/build.

/* eslint-disable */
import { createI18n } from "better-intl/runtime";
`;

/** Serialise the runtime-relevant config the `better-intl/runtime` helpers read. */
function emitIntlConfig(
	resolved: Record<string, LeafValue>,
	config: I18nConfig,
): string {
	const runtime = {
		defaultLocale: config.defaultLocale,
		locales: Object.keys(resolved),
		storage: config.storage,
	};
	return JSON.stringify(runtime, null, "\t");
}

/**
 * Emit the full generated module source: the `translations` object, the
 * `Locale` type, the explicit `getT` accessor, the `intlConfig` data, and the
 * ready-to-use `t` / `setLocale` / `updateLocale` produced by `createI18n` —
 * bound to `translations` + `intlConfig` so the app never re-passes them. The
 * input is the transposed `{ [locale]: resolvedTree }` object — each top-level
 * key is a locale.
 */
export function emit(
	resolved: Record<string, LeafValue>,
	config: I18nConfig,
): string {
	const body = emitLeafValue(resolved, 0);
	return `${HEADER}
export const translations = ${body} as const;

export type Locale = keyof typeof translations;

/** Explicit, locale-first accessor: \`getT("pt").homepage.title\`. */
export function getT<L extends Locale>(locale: L): (typeof translations)[L] {
	return translations[locale];
}

/** Runtime config for \`better-intl/runtime\`, baked into the helpers below. */
export const intlConfig = ${emitIntlConfig(resolved, config)} as const;

// Helpers bound to \`translations\` + \`intlConfig\` once. Import \`t\` anywhere
// (sync on both client and server); call \`setLocale()\` once per request in the
// root layout; call \`updateLocale(locale)\` to persist a new preference.
const i18n = createI18n(translations, intlConfig);
export const { t, setLocale, updateLocale } = i18n;
`;
}
